### ISSUE TITLE
Broken list format in "Blender basics" > "(EXERCISE) Interaction, selections, outliner"

### ISSUE THREAD

**Issue by PellelNitram** [surfsara-visualization/blendercourses#2]
I found a broken list format in the document "Blender basics" > "(EXERCISE) Interaction, selections, outliner".

Bullet point 18 is not formatted correctly. I guess it has something to do with the underlying source code not providing the correct indentation level.

Cheers!

**Comment by paulmelis** [comment]
Closing, was already fixed
